### ISSUE TITLE
README review

### ISSUE THREAD

**Issue by maggie-fu** [lstmemery/yeast-transcriptomics#6]
1) what you like about the README
It is interesting that the transcriptomes of 92 yeast strains were assessed. The readme is clear on what study is being proposed and where the data are stored.

2) what you find confusing or don't understand
There are quite a few typos in the readme file. e.g. "a numbre of yeast strains", "single celled organisms", and "clear documnetation". 
Additionally, I think the readme is less for the team members and more for the users, so the "Skills", "Suggested preparatory lessons", and "Hackathon Schedule" sections are confusing to me. Do I need "introductory knowledge of R, RNA expression analysis workflows, design thinking, and coding skills" to use this shiny app you are building?

3) what you think is missing
a. It would be great to get a more thorough explanation of how the yeast strains differ and what the stimuli are. 
b. Also, it would be nice if you have some hypotheses about how their transcriptomes are expected to change under each stimulus, especially because you mentioned the yeast stress response.
c. The "Goals" section will benefit from more details. For example, for "supervised clustering of expression data", you will be clustering the data based on what variables? What kind of data are the users supposed to visualize interactively?

**Comment by maggie-fu** [comment]
With the editing, the current version of the README is easy to comprehend. I can clearly understand the objective of the study and the deliverables for the project.
It is great to see that the ShinyApp is already online with some plots available for show. 
I only have one minor criticism for the current README, that is the first paragraph still suffers from grammatical errors, including several run-on sentences.

**Comment by sdemiriz** [comment]
Thank you for your feedback!
